config/routes.rb
Rails.application.routes.draw do
  root "posts#index"
  resources :posts do
    resources :comments, only: %i[create destroy]
    post :favourite, to: "favourite#create"
  end
  devise_for :users, controllers: {
    sessions: "users/sessions",
    passwords: "users/passwords",
    registrations: "users/registrations",
  }
  get "users/:id", to: "users#show", as: :user
  resources :contacts, only: %i[index new create destroy]
  get "which_post/:p", to: "which_post#show", as: :which_post
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  
  validates_presence_of :commenter
  validates :body, presence: true, uniqueness: true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    post = Post.find_by id: params[:post_id]
    comment = post.comments.new comment_params
    if comment.save
      flash[:notice] = "Comment created"
    else
      flash[:alert] = "Comment not created"
    end
    redirect_to post_path(post)
  end

  def destroy
    post = Post.find_by id: params[:post_id]
    comment = post.comments.find_by id: params[:id]
    if comment.destroy
      flash[:notice] = "Comment was deleted."
    else
      flash[:alert] = "Comment was not deleted."
    end
    redirect_to post_path(post), status: :see_other
  end

  private

  def comment_params
    params.require(:comment).permit %i[commenter body]
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<div style = "margin-top:5%">
  <% if comments.nil? or comments.empty? %>
    <p>There are no comments yet.</p>
  <% else %>
    <% comments.each do |comment| %>
      <% commenter = comment.commenter %>
      <div class = "panel panel-default">
        <div class = "panel-heading">
          <h5 class = "panel-title">
            <span class= "glyphicon glyphicon-user" aria-hidden="true"></span>
            <%= link_to commenter, user_path(commenter)+"?p=1" %>
          </h5>
          <span class= "glyphicon glyphicon-calendar" aria-hidden="true"></span>
          <%= time_tag comment.created_at %>
        </div>
        <%= render "body", body: comment.body.strip %>
        <% if comment.commenter.eql? current_user.username %>
          <!-- or the admin -->
          <a href="<%=post_comment_path(comment.post_id, comment)%>" data-turbo-method="delete" data-turbo-confirm="Sure to delete?"  class="btn btn-warning" role="button">
            <span class = "glyphicon glyphicon-trash" aria-hidden="true"></span> Delete
          </a>
        <% end %>
      </div>
    <% end %>
  <% end %>
</div>

app/views/comments/_form.html.erb
<div>
  <%= form_with model: [post, Comment.new] do |form| %>
    <div class = "form-group">
      <%= form.label :commenter, class: "control-label" %>
      <%= form.text_field :commenter, value: current_user.username, class: "form-control", readonly: true %>
    </div>
    <div class = "form-group">
      <%= form.label :comment, class: "control-label" %>
      <%= form.text_area :body, class: "form-control", rows: 5 %>
    </div>
    <div><%= form.submit %></div>
  <% end %>
</div>