config/routes.rb
Rails.application.routes.draw do
  root "posts#index"
  resources :posts do
    resources :comments, only: %i[create destroy]
    post :favourite, to: "favourite#create"
  end
  devise_for :users, controllers: {
    sessions: "users/sessions",
    passwords: "users/passwords",
    registrations: "users/registrations",
  }
  get "users/:id", to: "users#show", as: :user
  resources :contacts, only: %i[index new create destroy]
  get "which_post/:p", to: "which_post#show", as: :which_post
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts, dependent: :destroy
  has_many :favourites, dependent: :destroy
  has_many :comments, through: :posts, dependent: :destroy

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :username, uniqueness: true, format: /\A\w{5,}\z/
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  protected

  def after_resetting_password_path_for(resource)
    new_user_session_path
  end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    posts_path
  end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  def destroy
    super do
      flash[:notice] = "You have signed out"
      redirect_to posts_path, status: :see_other
      return
    end
  end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_in_params
    devise_parameter_sanitizer.permit(:sign_in, keys: [:username])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @user = User.find_by username: params[:id]
    if params[:p].eql? ?0
      @posts = Post.where id: @user.favourites.pluck(:post_id)
    else # params[:p].eql? ?1
      @posts = @user.posts
    end
  end
end

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h5>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h5>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_flash.html.erb
<% if which_flash %>
  <div class="alert alert-<%= which_flash %> alert-dismissible" role="alert">
    <span class = "glyphicon glyphicon-info-sign" aria-hidden="true"></span>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span>&times;</span>
    </button> <%= notice || alert %>
  </div>
<% end %>

app/views/users/shared/_footer.html.erb
<footer class = "blog-footer">
    Developed by Anietie. <br>
    Say <mark>bonjour</mark> on <%= link_to "github", "https://github.com/caanietie" %> or <%= link_to "twitter", "https://www.twitter.com/caanietie" %>
</footer>

app/views/users/shared/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top blog-masthead">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand navbar-link" href="#">
        <%= image_tag "logo.png", alt: "Brand Image", size: "60x40", style: "transform:translateY(-20%)" %>
      </a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
      <% if params[:controller].eql? "posts" and params[:action].eql? "index" %>
        <li class = "active">
      <% else %>
        <li>
      <% end %>
          <a href="<%= posts_path %>" class = "navbar-link">
            <span class = "glyphicon glyphicon-home" aria-hidden="true"></span> Home
          </a>
        </li>
      <% if params[:controller].eql? "contacts" %>
        <li class = "active">
      <% else %>
        <li>
      <% end %>
          <a href="<%= new_contact_path %>" class = "navbar-link">
            <span class = "glyphicon glyphicon-envelope" aria-hidden="true"></span> Contact
          </a>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li>
            <% handler = user_path(current_user.username)+"?p=1" %>
            <a href="<%=handler%>" class= "navbar-link">
              <span class = "glyphicon glyphicon-user" aria-hidden="true"></span>
              <%= current_user.username %>
            </a>
          </li>
          <li>
            <a href="<%=new_post_path%>" class="navbar-link">
              <span class = "glyphicon glyphicon-pencil" aria-hidden="true"></span> New Post
            </a>
          </li>
          <li>
            <a href="<%=destroy_user_session_path%>" class="btn btn-default" role="button" data-turbo-method="delete">
              <span class = "glyphicon glyphicon-log-out" aria-hidden="true"></span> Sign Out
            </a>
          </li>
        <% else %>
          <li>
            <a href="<%=new_user_session_path%>" class="navbar-link">
              <span class = "glyphicon glyphicon-log-in" aria-hidden="true"></span> Sign In
            </a>
          </li>
          <li>
            <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-default", role: :button %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/users/shared/_header_footer.html.erb
<%= render "users/shared/header" %>
<div class = "container">
  <div class="blog-header">
    <h2 class="blog-title">Members Only</h2>
    <p class="lead blog-description">Share Your Stories.</p>
  </div>
  <% which_flash = notice ? "info" : alert ? "warning" : nil %>
  <%= render "users/shared/flash", which_flash: which_flash %>
  <%= yield %>
</div>
<%= render "users/shared/footer" %>

app/views/users/shared/_links.html.erb
<div style = "margin-top: 4%">
  <%- if controller_name != 'sessions' %>
    <%= link_to "Log in", new_session_path(resource_name) %> to your account.<br />
  <% end %>

  <%- if devise_mapping.registerable? && controller_name != 'registrations' %>
    <%= link_to "Sign up", new_registration_path(resource_name) %> to create an account.<br />
  <% end %>

  <%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
    <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
  <% end %>

  <%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
    <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
  <% end %>

  <%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
    <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
  <% end %>

  <%#- if devise_mapping.omniauthable? %>
    <%#- resource_class.omniauth_providers.each do |provider| %>
      <%#= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
    <%# end %>
  <%# end %>
</div>