config/routes.rb
Rails.application.routes.draw do
  root "posts#index"
  resources :posts do
    resources :comments, only: %i[create destroy]
    post :favourite, to: "favourite#create"
  end
  devise_for :users, controllers: {
    sessions: "users/sessions",
    passwords: "users/passwords",
    registrations: "users/registrations",
  }
  get "users/:id", to: "users#show", as: :user
  resources :contacts, only: %i[index new create destroy]
  get "which_post/:p", to: "which_post#show", as: :which_post
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :favourites, dependent: :destroy

  validates :title, length: {minimum: 5}
  validates :body, uniqueness: true, length: {minimum: 50}
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: %i[index]

  def index
    if user_signed_in?
      redirect_to which_post_path(p: 1)
    else
      @posts = Post.all
    end
  end

  def show
    @post = Post.find_by id: params[:id]
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.new post_params
    if @post.save
      flash[:notice] = "Post was created"
      redirect_to @post
    else
      flash.now[:alert] = "Post was not created"
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @post = Post.find_by id: params[:id]
  end

  def update
    @post = Post.find_by id: params[:id]
    if @post.update post_params
      flash[:notice] = "Post was sucessfully updated"
      redirect_to @post
    else
      flash.now[:alert] = "Unable to update post"
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @post = Post.find_by id: params[:id]
    if @post.destroy
      flash[:info] = "Post is successfully deleted"
      redirect_to posts_path, status: :see_other
    else
      flash.now[:alert] = "Unable to delete post"
      render :show, status: :unprocessable_entity
    end
  end

  private

  def post_params
    params.require(:post).permit %i[title body]
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_body.html.erb
<div class = "panel-body">
  <% body.lines.each do |line| %>
    <p><%= line.strip %></p>
  <% end %>
</div>

app/views/posts/_form.html.erb
<%= form_with model: post do |form| %>
  <%= render "users/shared/error_messages", resource: post %>
  <div class = "form-group">
    <%= form.label :title, class: "control-label" %>
    <%= form.text_field :title, class: "form-control", required: true %>
  </div>
  <div class = "form-group">
    <%= form.label :body, class: "control-label" %>
    <%= form.text_area :body, class: "form-control", rows: 5, required: true %>
  </div>
  <div>
    <%= form.submit action, class: "btn btn-success form-control", style: "margin-bottom: 5px" %>
    <%= link_to "Back", :back, class: "btn btn-info form-control", role: :button %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<% if posts.nil? or posts.empty? %>
  <p>You do not have any post.</p>
<% else %>
  <% posts.each do |post| %>
    <% username = post.user.username %>
    <div class="blog-post panel panel-default">
      <div class = "panel-heading">
        <h4 class="blog-post-title"><%= post.title %></h4>
        <% if user_signed_in? %>
          <a href="<%=user_path(username)+'?p=1'%>" class="blog-post-meta">
            <span class = "glyphicon glyphicon-user" aria-hidden = "true"></span>
            <%=username %>
          </a><br>
        <% end %>
        <span class = "glyphicon glyphicon-calendar blog-post-meta" aria-hidden = "true"></span>
        <%= time_tag post.created_at, class: "blog-post-meta" %>
      </div>
      <div class = "panel-body">
        <p><%= post.body.lines[0] %>...</p> <%# The first paragraph %>
        <div style = "display:flex;gap:10%;margin-bottom:2.5%">
          <div>
              <span class = "badge"><%= post.comments.length %></span>
              <span class = "glyphicon glyphicon-comment" aria-hidden = "true"></span>
          </div>
          <div>
              <span class = "badge"><%= post.favourites.length %></span>
              <span class = "glyphicon glyphicon-heart" aria-hidden = "true"></span>
          </div>
        </div>
        <%= link_to "Continue reading", post_path(post), class: "btn btn-default", role: :button %>
      </div>
    </div>
  <% end %>
<% end %>

app/views/posts/edit.html.erb
<%= render "users/shared/header_footer" do %>
  <h2>Edit Post</h2>
  <%= render "form", post: @post, action: "Update Post" %>
<% end %>

app/views/posts/index.html.erb
<%= render "users/shared/header_footer" do %>
  <div class="row container">
    <div class="blog-main">
      <%= render "posts/post", posts: @posts %>
    </div>
  </div>
<% end %>

app/views/posts/new.html.erb
<%= render "users/shared/header_footer" do %>
  <h2>New Post</h2>
  <%= render "form", post: @post, action: "Create Post" %>
<% end %>

app/views/posts/show.html.erb
<%= render "users/shared/header_footer" do %>
  <%= render "which_post/pager", p: current_user.eql?(@post.user) ? ?1 : ?0 %>
  <div class = "blog-post">
    <div class = "panel panel-default">
      <div class = "panel-heading">
        <h4 class="blog-post-title"><%= @post.title %></h4>
        <% username = @post.user.username %>
        <a href="<%=user_path(username)+'?p=1'%>" class="blog-post-meta">
          <span class = "glyphicon glyphicon-user" aria-hidden = "true"></span> <%=username%>
        </a><br>
        <span class = "glyphicon glyphicon-calendar blog-post-meta" aria-hidden = "true"></span>
        <%= time_tag @post.created_at, class:"blog-post-meta" %>
        <div>
          <a href="<%=post_favourite_path(@post)%>" class = "btn btn-default" data-turbo-method="post">
            <span class="badge"><%= @post.favourites.length %></span>
            <span class = "glyphicon glyphicon-heart" aria-hidden="true"></span>
          </a>
          <% if current_user.eql? @post.user %>
            <a href="<%=edit_post_path%>" class="btn btn-default">
              <span class="glyphicon glyphicon-edit" aria-hidden="true"></span>
              Edit
            </a>
<%# TODO if user has not pin post show pin. active when pinned %>
<!--
<a href="#" class="btn btn-default">
<span class = "glyphicon glyphicon-pushpin" aria-hidden = "true"></span>
</a>
-->
            <a href="<%=post_path%>" class="btn btn-warning" data-turbo-method="delete" data-turbo-confirm="Sure to delete post?">
              <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
            </a>
          <% end %>
        </div>
      </div>
      <%= render "body", body: @post.body.strip %>
    </div>
    <div style = "margin-top:5%">
      <h3><span class = "glyphicon glyphicon-comment" aria-hidden="true"></span> Comments</h3>
      <%= render "comments/form", post: @post %>
      <%= render "comments/comment", comments: @post.comments %>
    </div>
  </div>
<% end %>